# Generated by Django 5.1.2 on 2024-10-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transa_id', models.IntegerField()),
                ('transa_tipo', models.CharField(max_length=3)),
                ('banco_oricod', models.CharField(max_length=34)),
                ('banco_orinom', models.CharField(blank=True, max_length=60, null=True)),
                ('banco_destcod', models.CharField(max_length=34)),
                ('banco_destnom', models.CharField(blank=True, max_length=60, null=True)),
                ('transa_trn', models.CharField(max_length=20)),
                ('fecha_lbtr', models.DateField()),
                ('transa_monto', models.DecimalField(decimal_places=2, max_digits=13)),
                ('transa_moneda', models.CharField(max_length=3)),
                ('cuenta_origen', models.CharField(max_length=34)),
                ('cuenta_destino', models.CharField(max_length=34)),
                ('transa_comentario', models.CharField(blank=True, max_length=210, null=True)),
                ('transa_mensajeerror', models.CharField(blank=True, max_length=210, null=True)),
                ('transa_codigo', models.IntegerField(blank=True, null=True)),
                ('transa_estatus', models.CharField(max_length=2)),
                ('transa_tipocta', models.CharField(max_length=2)),
                ('identif_benef', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_benef', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_reg', models.DateTimeField()),
                ('identif_ctaorigen', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_ctaorigen', models.CharField(blank=True, max_length=130, null=True)),
                ('descrip_dev', models.CharField(blank=True, max_length=60, null=True)),
                ('dev_trnorg', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
