# Generated by Django 5.1.2 on 2024-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('Transa_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Transa_Tipo', models.CharField(max_length=3)),
                ('Banco_Oricod', models.CharField(max_length=34)),
                ('Banco_Orinom', models.CharField(blank=True, max_length=60, null=True)),
                ('Banco_destcod', models.CharField(max_length=34)),
                ('Banco_Destnom', models.CharField(blank=True, max_length=60, null=True)),
                ('Transa_TRN', models.CharField(max_length=20)),
                ('Fecha_LBTR', models.DateField()),
                ('Transa_Monto', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Transa_Moneda', models.CharField(max_length=3)),
                ('Cuenta_origen', models.CharField(max_length=34)),
                ('Cuenta_destino', models.CharField(max_length=34)),
                ('Transa_comentario', models.CharField(blank=True, max_length=210, null=True)),
                ('Transa_mensajeerror', models.CharField(blank=True, max_length=210, null=True)),
                ('Transa_Codigo', models.IntegerField(blank=True, null=True)),
                ('Transa_Estatus', models.CharField(max_length=2)),
                ('Transa_Tipocta', models.CharField(max_length=2)),
                ('Identif_Benef', models.CharField(blank=True, max_length=20, null=True)),
                ('Nombre_Benef', models.CharField(blank=True, max_length=60, null=True)),
                ('Fecha_Reg', models.DateTimeField()),
                ('Identif_Ctaorigen', models.CharField(blank=True, max_length=15, null=True)),
                ('Nombre_Ctaorigen', models.CharField(blank=True, max_length=130, null=True)),
                ('Descrip_Dev', models.CharField(blank=True, max_length=60, null=True)),
                ('Dev_TRNorg', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
