# Generated by Django 5.1.2 on 2024-11-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='Fecha_Reg',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
